#!/bin/sh
# from: https://wiki.archlinux.org/index.php/i3#Shutdown.2C_reboot.2C_lock_screen

lock() {
    #gnome-screensaver-command -l
    light-locker-command -l
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
	systemctl reboot
        #gksudo -- shutdown -r now
        ;;
    shutdown)
	systemctl poweroff
        #gksudo -- shutdown -h now
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
