#!/bin/sh
# from: https://wiki.archlinux.org/index.php/i3#Shutdown.2C_reboot.2C_lock_screen

readonly wm_msg=swaymsg

case "$1" in
    lock)
        # lock needs to be external command
        lock
        ;;
    logout)
        if [ -x .local/bin/logout ]; then
            logout
        else
            $wm_msg exit
        fi
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        #gksudo -- shutdown -r now
        ;;
    shutdown)
        systemctl poweroff
        #gksudo -- shutdown -h now
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
